### ISSUE TITLE
enhancement: 채점 측 여러 개의 소스코드 업로드 기능

### ISSUE THREAD

**Issue by jubin-park** [hyunchan-park/JOTA-dmoj-online-judge#4]
**목표**
* C (gcc) Judge 한정하여 구현
* Grader(채점자) 측에서 additional & multiple 소스(*.c)와 헤더(*.h)를 추가한다.
* Submitter(제출자) 측에서 부분적으로 Grader가 업로드한 소스 파일의 일부를 include 한다.
  * e.g.
    1. Grader는 문제와 함께 LinkedList 를 구현한 소스코드를 첨가한다.
    2. Grader가 업로드한 LinkedList 코드를 자동으로 Submitter 코드가 include 하기만 하면, Submitter는 LinkedList 구현코드까지 함께 제출할 필요가 없으며, LinkedList 관련 연산을 사용한 코드만 제출하면 된다.
* `signature_grader` 노드 멤버 `entry`, `header`가 gcc 컴파일 옵션과 관련돼있는지 확인

**참고할 주제**
* Function Signature Grading: https://dmoj.readthedocs.io/en/latest/problem_format/custom_graders/#function-signature-grading-ioi-style
* Custom Checkers: https://dmoj.readthedocs.io/en/latest/problem_format/custom_checkers/

**Comment by hyunchan-park** [comment]
좋습니다. 진행 부탁드립니다.

**Comment by jubin-park** [comment]
실수로 assignment 지웠습니다. 다시 요청드립니다.

**Comment by fhqlatm** [comment]
**Additional Steps**

* Extend to C++ using g++
* Submitter가 제출한 multiple sources를 탐색하여 Grader 측에서 제공된 소스코드(.c) 혹은 헤더(.h)의  포함 여부를 판별하고 해당 source가 존재하지 않는 경우 자동으로 include 하여 judge 수행 


**Referecing Judge Code Example**

* /home/ubuntu/jota/dmojsite/lib/python3.8/site-packages/dmoj/problem.py
* /home/ubuntu/jota/dmojsite/lib/python3.8/site-packages/dmoj/judge.py
* /home/ubuntu/jota/dmojsite/lib/python3.8/site-packages/dmoj/graders/base.py
* /home/ubuntu/jota/dmojsite/lib/python3.8/site-packages/dmoj/graders/signature.py

```python3
Traceback (most recent call last):
  File "/home/ubuntu/jota/dmojsite/lib/python3.8/site-packages/dmoj/problem.py", line 198, in __missing__
    with open(os.path.join(self.problem.root_dir, key), 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/jota/problems/gradertest/header.h'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/jota/dmojsite/lib/python3.8/site-packages/dmoj/judge.py", line 404, in _worker_process_main
    ipc_msg = next(case_gen)
  File "/home/ubuntu/jota/dmojsite/lib/python3.8/site-packages/dmoj/judge.py", line 443, in _grade_cases
    self.grader = problem.grader_class(
  File "/home/ubuntu/jota/dmojsite/lib/python3.8/site-packages/dmoj/graders/base.py", line 11, in __init__
    self.binary = self._generate_binary()
  File "/home/ubuntu/jota/dmojsite/lib/python3.8/site-packages/dmoj/graders/signature.py", line 18, in _generate_binary
    header = self.problem.problem_data[handler_data['header']]
  File "/home/ubuntu/jota/dmojsite/lib/python3.8/site-packages/dmoj/problem.py", line 202, in __missing__
    zipinfo = self.archive.getinfo(key)
  File "/usr/lib/python3.8/zipfile.py", line 1441, in getinfo
    raise KeyError(
KeyError: "There is no item named 'header.h' in the archive"
```

**Comment by fhqlatm** [comment]
@hyunchan-park 
Team: (@jubin-park, @fhqlatm) 
팀프로젝트 진행하겠습니다. 감사합니다.

**Comment by jubin-park** [comment]
@fhqlatm

## BaseGrader
- 최상위 추상클래스
`/home/ubuntu/jota/dmojsite/lib/python3.8/site-packages/dmoj/graders/base.py`

## StandardGrader < BaseGrader
- 표준 채점기
`/home/ubuntu/jota/dmojsite/lib/python3.8/site-packages/dmoj/graders/standard.py`

## SignatureGrader < StandardGrader
- 시그니처 채점기
- **주목해야 할 부분**
`/home/ubuntu/jota/dmojsite/lib/python3.8/site-packages/dmoj/graders/signature.py`

```python3
class SignatureGrader(StandardGrader):
    def _generate_binary(self):
        siggraders = ('C', 'C11', 'CPP03', 'CPP11', 'CPP14', 'CPP17', 'CPP20', 'CLANG', 'CLANGX')

        if self.language in siggraders:
            aux_sources = {}
            handler_data = self.problem.config['signature_grader']

            entry_point = self.problem.problem_data[handler_data['entry']]
            header = self.problem.problem_data[handler_data['header']]

            submission_prefix = '#include "%s"\n' % handler_data['header']
            if not handler_data.get('allow_main', False):
                submission_prefix += '#define main main_%s\n' % uuid.uuid4().hex

            aux_sources[self.problem.id + '_submission'] = utf8bytes(submission_prefix) + self.source

            aux_sources[handler_data['header']] = header
            entry = entry_point
            return executors[self.language].Executor(
                self.problem.id, entry, aux_sources=aux_sources, defines=['-DSIGNATURE_GRADER'],
            )
        else:
            raise InternalError('no valid runtime for signature grading %s found' % self.language)
```

* handler_data['hedaer']를 배열 자료형으로 수정 필요
* entry는 main 함수의 위치이므로 배열로 만들 필요가 없음
* 대신 *.c 소스 파일을 복수로 받을 수 있도록 config 데이터에 새 key-value 쌍을 추가해야 할 필요할 것으로 예상
* yaml 문법: https://www.cloudbees.com/blog/yaml-tutorial-everything-you-need-get-started

**Comment by hyunchan-park** [comment]
> 실수로 assignment 지웠습니다. 다시 요청드립니다.

다시 설정하였습니다. 수고 많습니다!

**Comment by jubin-park** [comment]
# Signature.py 분석하기
## SignatureGrader Members

**self**
```python3
{
  # <class 'bytes'>
  'source': b'bool is_valid(int a)\r\n{\r\n    return true;\r\n}', # 제출 코드

  # <class 'str'>
  'language': 'CPP03', # 제출 코드 언어

  # <class 'dmoj.problem.Problem'>
  'problem': <dmoj.problem.Problem object at 0x7f2d50dfa880>

  # <class 'dmoj.judge.JudgeWorker'>
  'judge': <dmoj.judge.JudgeWorker object at 0x7f2d5058ef10>
}
```

**self.problem**
```python3
# <class 'dmoj.problem.Problem'>
{
  # <class 'str'>
  'id': 'gradertest',

  # <class 'float'>
  'time_limit': 10.0,

  # <class 'int'>
  'memory_limit': 65536,

  # <class 'dmoj.config.ConfigNode'>
  'meta': <dmoj.config.ConfigNode object at 0x7f2d50e0f2b0>,

  # <class 'str'>
  'root_dir': '/home/ubuntu/jota/problems/gradertest',

  # <class 'dmoj.problem.ProblemDataManager'> <-- 파일명을 넘기면 File read 발생
  'problem_data': {},

  # <class 'dict'>
  '_checkers': {},

  # <class 'dmoj.problem.ProblemConfig'>
  'config': <dmoj.problem.ProblemConfig object at 0x7f2d50e0f4c0>
}
```

**self.problem.meta**
```python3
# <class 'dmoj.config.ConfigNode'>
{
  # <class 'bool'>
  'dynamic': True,

  # <class 'dict'>
  'raw_config': {'pretests-only': False, 'in-contest': None, 'attempt-no': 5, 'user': 1},

  # <class 'NoneType'>
  'parent': None
}
```

**self.problem.config**
```python3
# <class 'dmoj.problem.ProblemConfig'>
{
    # <class 'bool'>
    'dynamic': True,

    # <class 'dict'>
    'raw_config': {
        'wall_time_factor': 3,
        'output_prefix_length': 0,
        'output_limit_length': 25165824,
        'binary_data': False,
        'short_circuit': True,
        'points': 1,
        'symlinks': {},
        'meta': {
            'pretests-only': False,
            'in-contest': None,
            'attempt-no': 5,
            'user': 1
        },

        # <class 'str'>
        'archive': 'data.zip',

        # <class 'dmoj.config.ConfigNode'>
        'signature_grader': {'dynamic': True, 'raw_config': {'entry': 'handler.c', 'header': 'header.h'}, 'parent': <dmoj.problem.ProblemConfig object at 0x7f2d50e0f4c0>}

        # <class 'list'>
        'test_cases': [
            # <class 'dict'>
            {
                'in': 'siggrade.1.in',
                'out': 'siggrade.1.out',
                'point': 50
            },
            {
                'in': 'siggrade.2.in',
                'out': 'siggrade.2.out',
                'point': 10
            }
        ]},
    },

    # <class 'NoneType'>
    'parent': None
}
```

**self.judge**
```python3
# <class 'dmoj.judge.JudgeWorker'>
{
    # <class 'dmoj.judge.Submission'>
    'submission': Submission(
        id=95, # 제출 번호
        problem_id='gradertest', # 문제 코드
        language='CPP03', # 제출 언어

        # <class 'str'>
        source='bool is_valid(int a)\r\n{\r\n    return true;\r\n}',

        time_limit=10.0,
        memory_limit=65536,
        short_circuit=False,
        meta={
            'pretests-only': False,
            'in-contest': None,
            'attempt-no': 5,
            'user': 1
        }
    ),

    '_abort_requested': False,

    'grader': None,

    'worker_process_conn': <multiprocessing.connection.Connection object at 0x7f2d50576fd0>,

    'worker_process': <Process name='DMOJ Judge Handler for gradertest/95' parent=2637 started>
}
```

**파일을 바이트로 read**
* ProblemDataManager < dict 이고, element 참조 시 f.read() 하도록 오버라이딩 한 것

```python3
handler_data = self.problem.config['signature_grader']

entry_point = self.problem.problem_data[handler_data['entry']]
# => b'#include "header.h"\n#include <stdio.h>\n#include <stdbool.h>\n\nstatic int n;\n\nint main()\n{\n    scanf("%d", &n);\n    bool valid = is_valid(n); // Defined in header\n    printf(valid ? "correct" : "wrong");\n    return 0;\n}'

header = self.problem.problem_data[handler_data['header']]
# => b'#ifndef _GRADER_HEADER_INCLUDED\n#define _GRADER_HEADER_INCLUDED\n#include <stdbool.h>\nbool is_valid(int);\n#endif'
```

## aux_sources ⭐⭐⭐
**<`key`: `value`> Pair 구조**
  1. <`self.problem.id + 'submission'` : `제출자측 코드 내용`>
  2. <`header 파일 이름` : `header 파일 내용`>
```
# <class 'dict'>
{
  'gradertest_submission': b'#include "header.h"\n#define main main_f8c0af95d5cc4d1387266ac89a49cc6d\nbool is_valid(int a)\r\n{\r\n    return true;\r\n}',
  'header.h': b'#ifndef _GRADER_HEADER_INCLUDED\n#define _GRADER_HEADER_INCLUDED\n#include <stdbool.h>\nbool is_valid(int);\n#endif'
}
```

## Executor modules
* executors
```python3
from dmoj.executors import executors

# <class 'dict'>
{
  'AWK': <module 'dmoj.executors.AWK' from '/home/ubuntu/jota/judge/dmoj/executors/AWK.py'>,
  'BF': <module 'dmoj.executors.BF' from '/home/ubuntu/jota/judge/dmoj/executors/BF.py'>,
  'C': <module 'dmoj.executors.C' from '/home/ubuntu/jota/judge/dmoj/executors/C.py'>,
  'C11': <module 'dmoj.executors.C11' from '/home/ubuntu/jota/judge/dmoj/executors/C11.py'>,
  'CPP03': <module 'dmoj.executors.CPP03' from '/home/ubuntu/jota/judge/dmoj/executors/CPP03.py'>,
  'CPP11': <module 'dmoj.executors.CPP11' from '/home/ubuntu/jota/judge/dmoj/executors/CPP11.py'>,
  'CPP14': <module 'dmoj.executors.CPP14' from '/home/ubuntu/jota/judge/dmoj/executors/CPP14.py'>,
  'CPP17': <module 'dmoj.executors.CPP17' from '/home/ubuntu/jota/judge/dmoj/executors/CPP17.py'>,
  'GAS64': <module 'dmoj.executors.GAS64' from '/home/ubuntu/jota/judge/dmoj/executors/GAS64.py'>,
  'PERL': <module 'dmoj.executors.PERL' from '/home/ubuntu/jota/judge/dmoj/executors/PERL.py'>,
  'PY3': <module 'dmoj.executors.PY3' from '/home/ubuntu/jota/judge/dmoj/executors/PY3.py'>,
  'SED': <module 'dmoj.executors.SED' from '/home/ubuntu/jota/judge/dmoj/executors/SED.py'>,
  'TEXT': <module 'dmoj.executors.TEXT' from '/home/ubuntu/jota/judge/dmoj/executors/TEXT.py'>
}
```

### C.py
`/home/ubuntu/jota/judge/dmoj/executors/C.py`
```python3
from .gcc_executor import GCCExecutor

class Executor(GCCExecutor):
    command = 'gcc'
    flags = ['-std=c99']
    ext = 'c'
    name = 'C'
    test_program = '''
#include <stdio.h>

int main() {
    int ch;
    while ((ch = getchar()) != EOF)
        putchar(ch);
    return 0;
}
'''
```

### C11.py
`/home/ubuntu/jota/judge/dmoj/executors/C11.py`
```python3
from .gcc_executor import GCCExecutor

class Executor(GCCExecutor):
    command = 'gcc11'
    flags = ['-std=c11']
    command_paths = ['gcc']
    ext = 'c'
    name = 'C11'
    test_program = '''
#include <stdio.h>

int main() {
    int ch;
    while ((ch = getchar()) != EOF)
        putchar(ch);
    return 0;
}
'''
```

* GCCExecutor 소스코드 참고하기
  * `home/ubuntu/jota/judge/dmoj/executors/gcc_executor.py`
* 각 C Lang Executor 클래스의 flags 배열에 aux_sources를 전달해서 key 중 *.c  소스파일만 골라서 linking 해야 한다.

**Comment by hyunchan-park** [comment]
여기 모여있는 내용들 나중에 문서로 정리해주시면 감사하겠습니다ㅎㅎ

**Comment by jubin-park** [comment]
> 여기 모여있는 내용들 나중에 문서로 정리해주시면 감사하겠습니다ㅎㅎ

알겠습니다.

현재 issue는 Site보다는 Judge와의 관련이 큽니다.
따라서 JOTA-dmoj-judge-server 저장소로 Transfer Issue 해주시면 감사하겠습니다.
